"""add word

Revision ID: 19b244e1b5
Revises: None
Create Date: 2014-08-29 17:43:08.827519

"""

# revision identifiers, used by Alembic.
revision = '19b244e1b5'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.Unicode(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('words')
    ### end Alembic commands ###
