"""remove Word.score

Revision ID: 231fe018df3
Revises: 118880d89dc
Create Date: 2014-09-15 15:24:35.759882

"""

# revision identifiers, used by Alembic.
revision = '231fe018df3'
down_revision = '118880d89dc'

from alembic.op import drop_column, add_column, get_bind, execute
from sqlalchemy import INTEGER, Column


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    engine = get_bind().engine
    if engine.name == 'sqlite':
        sql = '''
            CREATE TEMP TABLE word_dump (
                id INTEGER NOT NULL,
                word VARCHAR NOT NULL,
                lyrics_id INTEGER NOT NULL,
                freq INTEGER,
                PRIMARY KEY (id)
            );

            ---

            INSERT INTO word_dump
            (id, word, lyrics_id, freq)
            SELECT id, word, lyrics_id, freq
            FROM words;

            ---
            DROP TABLE words;
            ---
            CREATE TABLE words (
                id INTEGER NOT NULL,
                word VARCHAR NOT NULL,
                lyrics_id INTEGER DEFAULT '0' NOT NULL,
                freq INTEGER,
                PRIMARY KEY (id)
            );

            ---
            INSERT INTO words
            (id, word, lyrics_id, freq)
            SELECT id, word, lyrics_id, freq
            FROM word_dump;
        '''
        for s in sql.split('---'):
            execute(s)
    else:
        drop_column('words', 'score')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    add_column('words', Column('score', INTEGER(), nullable=True))
    ### end Alembic commands ###
