"""add Word.lyrics_id

Revision ID: 446136f288
Revises: 2f60a39d9dc
Create Date: 2014-09-15 14:42:02.659340

"""

# revision identifiers, used by Alembic.
revision = '446136f288'
down_revision = '2f60a39d9dc'

from alembic.op import (add_column, drop_column, create_foreign_key,
                        drop_constraint, get_bind)
from sqlalchemy.types import Integer
from sqlalchemy.schema import ForeignKey, Column




def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    engine_name = get_bind().engine.name
    add_column('words',
               Column('lyrics_id',
                      Integer,
                      nullable=False,
                      server_default='0'))
    if engine_name == 'postgresql':
        create_foreign_key('words_lyrics_id_fkey', 'words',
                           'lyrics', ['lyrics_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    engine_name = get_bind().engine.name
    if engine_name == 'postgresql':
        drop_constraint('words_lyrics_id_fkey', 'words')
    drop_column('words', 'lyrics_id')
    ### end Alembic commands ###
